version: '3.8'

services:
  database:
    image: mariadb:10.6.12
    container_name: "${APP_NAME}_database"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/database/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - app_network

  service:
    image: golang:1.23.1-alpine
    container_name: "${APP_NAME}_service"
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      CONFIG_PATH: ./config/dev.yaml
    networks:
      - app_network
    command: ["tail", "-f", "/dev/null"]

volumes:
  db_data:

networks:
  app_network:
