env: "dev"
storage:
  host: "database"
  port: 3306
  user: "user_wiki_rocketfirm"
  password: "password"
  database: "db_wiki_rocketfirm"
  migration: ""
clients:
  http:
    wiki:
      host: "https://wiki.rocketfirm.com"
      timeout: 5s
      token_id: ""
      token_secret: ""
      paths:
        pages_export_markdown: "/api/pages/export/%d/markdown"
